### ISSUE TITLE
[Content] - add info for opengl driver 

### ISSUE THREAD

**Issue by msurguy** [processing/processing-pi-website#22]
Prompted by user "micuat" in the the thread on https://discourse.processing.org/t/where-is-the-main-documentation/1757, some of the docs on opengl driver are not currently found on this website. 

Perhaps we can move the contents from https://github.com/processing/processing/wiki/Raspberry-Pi to this website and make a note on the wiki to come here instead. 

What do you think @gohai ?

**Comment by gohai** [comment]
@msurguy Good idea Maks, I started the process here: c1470ab9f5018cb85f3c575635d6f32a5b30e0b2

@micuat You'll get the best possible experience currently by downloading and using our pre-built [image](https://pi.processing.org/get-started/). If you run into any issues with that please holler!

I agree that the situation with the multiple graphics drivers is currently a bit confusing. The Raspberry Pi Foundation has been working since years on the "new" driver, which is feature-wise _almost_ en-par with the old one. Unfortunately the features that are not quite ready pertain to video decoding and use of the camera - so things that people probably do care about. I am hopeful that they will release a Raspbian version in the fall that will finally make the "new" driver the default. At this point we'll revisit the OpenGL and video situation - make sure that everything works, and drop support for the legacy driver going forward.

**Comment by gohai** [comment]
PS for @msurguy: I think ultimately we should strive to move information from this page to more specific places - e.g. the information on how to enable the I2C or SPI bus (on vanilla installations of Raspbian) could be moved to an overview site for the I2C/SPI classes respectively.
